### ISSUE TITLE
deps: add `tailwindcss-aspect-ratio`

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#10]
A plugin that provides a composable API for giving elements a fixed aspect ratio. This will be useful on pages with multiple images, such as blog listings or galleries.

From their readme:

---

## Usage

Combine the `aspect-w-{n}` and `aspect-h-{n}` classes to specify the aspect ratio for an element:

```html
<div class="aspect-w-16 aspect-h-9">
  <iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
```

Use `aspect-none` to remove any aspect ratio behavior:

```html
<div class="aspect-w-16 aspect-h-9 lg:aspect-none">
  <!-- ... -->
</div>
```

https://github.com/tailwindlabs/tailwindcss-aspect-ratio

**Comment by kentcdodds** [comment]
Sweet! Thanks. I'll add this 👍
