### ISSUE TITLE
Layout Shift

### ISSUE THREAD

**Issue by tsteckenborn** [kentcdodds/remix-kentcdodds#112]
On all top navigation pages but Discord and About the layout shifts for me after a few seconds. Probably this is not the preferred behavior.

![06-08-_2021_17-52-10](https://user-images.githubusercontent.com/50519619/128537924-60cc4914-47f8-4358-8edd-5efe1da8daf5.gif)

**Comment by smeijer** [comment]
We want to undo this commit. It looks sweet when having the right screen height, but annoying in all other cases.

https://github.com/kentcdodds/remix-kentcdodds/pull/109/commits/b7c552cc501a7e850422281da38b3eee67b8b0f7?diff=unified&w=1
