### ISSUE TITLE
Footer at 1024px

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/remix-kentcdodds#121]
The footer columns look sub-optimal around 1024px window width (Firefox 92, MacOS):

<img width="1060" alt="Screenshot 2021-09-22 at 15 54 03" src="https://user-images.githubusercontent.com/1087670/134357287-01cfccc1-95ad-440e-a695-9147d7fde363.png">

Especially the padding for the email field looks odd - it still seems to be functional, so just a cosmetic issue.

**Comment by kentcdodds** [comment]
How'd your "Learn more" turn green? 🤔 It should be your team color! Weird!

Yeah, I'll give this a look. Maybe we'll just have the newsletter thing take up a full row above the rest of this stuff.

**Comment by smeijer** [comment]
It's might be good enough to just switch to the "tablet breakpoint" sooner. 

![Screenshot_20210922-182339](https://user-images.githubusercontent.com/1196524/134383527-582a3a76-e0f4-4aeb-8a15-dc0ebcdeb193.jpg)

**Comment by Aprillion** [comment]
ah sorry about the color, I was messing up with CSS variables investigating #122 (the team color works fine on all pages except he blog)

**Comment by kentcdodds** [comment]
> It's might be good enough to just switch to the "tablet breakpoint" sooner.

Do you know how to do that @smeijer? 😅

**Comment by smeijer** [comment]
Would you believe me if I said no? :sweat_smile: 

Pull at #132

**Comment by kentcdodds** [comment]
Fixed. Thanks!
