### ISSUE TITLE
Blog is blue instead of team color

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/remix-kentcdodds#122]
Link color in the Blog section is blue (both https://kent.dev/blog and particular blogs), while all other sections reflect my chosen team color. Even if that is intended, I would prefer my team color just like elsewhere on the site 😅

**Comment by kentcdodds** [comment]
The way that works is whichever team is the overall leader is the color of the `/blog` page and whichever team is the leader of a specific post is the color of that post's page. I can understand how this might be a bit confusing though. Might be worth just not doing this for the `/blog` page... Do you think there's a way to make it more clear why the color is the way it is?

**Comment by Aprillion** [comment]
I suspected it could be something to do with the "winning" team:
<img width="131" alt="Screenshot 2021-09-22 at 18 30 19" src="https://user-images.githubusercontent.com/1087670/134384397-22108a8e-8590-4f70-a59f-a10b534302b2.png">

...but no easy way to tell that the color is same as the winning team on purpose or a bug 🤔
..perhaps if the header/footer remained the same color and only the links inside a blog would change?

**Comment by kentcdodds** [comment]
> ..perhaps if the header/footer remained the same color and only the links inside a blog would change?

Yeah, I'm thinking that's what I'll do. Probably the same for the blog pages as well (right now it's everything on those pages as well).
