### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/remix-kentcdodds#124]
Not sure if the credits page https://kent.dev/credits will be populated automatically in production, but currently the content looks unfinished 😅
<img width="1330" alt="Screenshot 2021-09-22 at 16 40 08" src="https://user-images.githubusercontent.com/1087670/134365381-fd19e0fa-2caa-48d5-a692-69c92a7fed86.png">

**Comment by kentcdodds** [comment]
Oh yeah 😅 I still need to get the bios of folks who contributed. Thanks for the reminder!

**Comment by kentcdodds** [comment]
Note to self: Make sure to add a "thanks to people who reviewed the site and have made PRs" etc...

**Comment by kentcdodds** [comment]
This is done!
