### ISSUE TITLE
Calls - episode thumbnail

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/remix-kentcdodds#125]
a) Thumbnail for episode 11 on https://kent.dev/calls did not load:

<img width="639" alt="Screenshot 2021-09-22 at 16 45 57" src="https://user-images.githubusercontent.com/1087670/134366121-f4b88596-1cbd-4b5d-9464-91aee0ee3dbe.png">

b) Not sure if using text already visible on screen as image alt would be optimal for screen-reader experience. The text is already wrapped inside the same `<a>` link as the image, so I would leave `alt=""` for the purely decorative image...

**Comment by Aprillion** [comment]
(nitpicking) Let me also frown a little about the doom of divs inside `<a>`, but that shouldn't break the experience for anyone, so probably not very important to improve HTML validity ¯\\\_(ツ)_/¯
<img width="702" alt="Screenshot 2021-09-22 at 16 52 48" src="https://user-images.githubusercontent.com/1087670/134367594-30115ae8-9104-423f-95fc-01cdf0d53470.png">

**Comment by kentcdodds** [comment]
Good point about the `alt=""`. I'll do that. As for "HTML validity":

> The a element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g. buttons or other links).

- [w3.org](https://www.w3.org/TR/2011/WD-html5-20110525/text-level-semantics.html#the-a-element) :)
