### ISSUE TITLE
pre-commit tries to delete redis cache

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#20]
The pre-commit hook tries to delete the Redis cache from the running instance, which resulted in an error at my system. The fix was to stop my dev environment and delete the cache before I `git commit`.

```
> kentcdodds.com@1.0.0 validate
> kcd-scripts validate

[build] /home/smeijer/dev/remix-kentcdodds/node_modules/rimraf/bin.js:46
[build]       throw er
[build]       ^
[build] 
[build] [Error: EACCES: permission denied, unlink './.cache/redis/dump.rdb'] {
[build]   errno: -13,
[build]   code: 'EACCES',
[build]   syscall: 'unlink',
[build]   path: './.cache/redis/dump.rdb'
[build] }
[build] npm run build --silent exited with code 1
--> Sending SIGTERM to other processes..
[typecheck] npm run typecheck --silent exited with code SIGTERM
husky > pre-commit hook failed (add --no-verify to bypass)
```

I'll see if it keeps occurring, or if it's a one-time thing. Just wanted to dump this somewhere.

**Comment by smeijer** [comment]
Definitely a permission thing between the user that runs `git commit`, and the user running `redis`.

**Comment by smeijer** [comment]
Maybe related, but I also have some weirdness in starting the env. Every time I start after deleting the Redis cache, I get the following error, which can be fixed by running `npx prisma migrate reset -f`

```
Remix-0    | Failure getting user from session ID: PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Remix-0    | Invalid `prisma.session.findUnique()` invocation:
Remix-0    |   The table `public.Session` does not exist in the current database.
```

Also, cypress doesn't run locally. Something weird must be going on here.

**Comment by kentcdodds** [comment]
That's very strange! I haven't experienced any of the things you're talking about. The migrate thing is odd as well because prisma knows nothing about the redis server at all. Very odd! Maybe we should just get rid of the deletion. If you need to bust the cache you can add `?bust-cache=true` to the end of any URL that loads content and it'll delete that thing from the cache.

**Comment by kentcdodds** [comment]
I just pushed that change so `npm run clean` will no longer delete the redis cache. Maybe in the future we can execute redis commands to clear it properly.

**Comment by kentcdodds** [comment]
I think this has been resolved right?

**Comment by smeijer** [comment]
It has indeed.
