### ISSUE TITLE
do something with `codesandbox` button

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#21]
Some blogs have `edit on codesandbox` buttons. I think it would be nice if they were positioned inside the code block, instead of on the paragraph below. 

What do you think? Maybe in the top right corner?

![image](https://user-images.githubusercontent.com/1196524/124106256-55713780-da64-11eb-9ffd-0498a7b9f272.png)

**Comment by kentcdodds** [comment]
Yeah, I like that idea a lot!

**Comment by kentcdodds** [comment]
I don't think this is worth doing anything with right now.
