### ISSUE TITLE
idea: use team color for focus styles

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#23]
Random thought:

If we can set the team color as a css var like, we could use that in `tailwind.config` for `team.current`, and then do something like:

```jsx
<input className="focus:ring-team-current" />
```

That way, the focus color of inputs, buttons, and links, could be based on the team color.

**Comment by kentcdodds** [comment]
YES! Let's do that. Anything to make the team thing more a part of the experience I'm all for. I'm also considering making multiple versions of syntax highlighting that are tweaked for each team color 😁

**Comment by kentcdodds** [comment]
I think this has been done 👍
