### ISSUE TITLE
Sign up flow continuation

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/remix-kentcdodds#29]
I made it so you can leave onboarding and come back later. However, that means people might forget which email address they used. So I just put it in the greeting on the sign up page:

![image](https://user-images.githubusercontent.com/1500684/124336895-3c987d00-db5d-11eb-9690-16c3303b74ca.png)

Maybe we should go back to the original design of having an input field (but make it read only). I'm open to suggestions.

Another thing this means is that people may want to "log out" of the account they don't yet have set up (if they want to use a different email) so I think that means we'll need the logout button again. But I don't want to call it "logout." I think I'd want it to be called "Cancel setup" or something. Thoughts?

**Comment by smeijer** [comment]
I think we should add the email input back, and either figure out a good style to show that it isn't editable (only a border and no background maybe?), or just make it editable.

What's stopping us from letting the user change their email there already? Changing it would require us to send them an confirmation mail, but I think it wouldn't be a bad thing to have. Both here, as well as on `/me`.

Regarding logout. We can add a cancel link next to the "create account" button. Should we call it more explicit? `remove profile`? Even though we don't really have a profile at this stage, I think it makes it more clear that they end up having no account. 

I'm aware that they don't have it already, this is the sign-up page. But the logged in state represented by the profile picture in the navbar, might have them confused.

**Comment by kentcdodds** [comment]
Yeah, we can add the email input. I don't want to allow them to change it though. Just complicates things. Let's just call the button: "Cancel"

Would love to know what Gil has to say about this though.

**Comment by kentcdodds** [comment]
I think we're set here 👍

**Comment by kentcdodds** [comment]
Oh, jk, I forgot we need a Cancel button 😅

**Comment by kentcdodds** [comment]
Got that added 👍
