### ISSUE TITLE
tag filter on `/blog` doesn't support tags with spaces

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#31]
The tag filter is a bit buggy, because we split on space while some tags include spaces. Because of that, tags like `open source` cannot be deselected.

https://github.com/kentcdodds/remix-kentcdodds/blob/f1681e5a37456c8af173439ba94bbf13d008ba09/app/routes/blog/index.tsx#L119-L129

**Comment by andraspalasti** [comment]
I think this could be resolved by replacing the mentioned code with this:
```
function toggleTag(tag: string) { 
   setQuery(q => { 
     const newQuery = q.includes(tag) 
       ? data.tags.filter(t => t.includes(q) && t !== tag) 
       : `${q} ${tag}` 
     return newQuery.trim() 
   }) 
 } 
```
This is a bit slower approach but you don't have to deal with escaping the tags.
Also I don't have a remix license so i didn't test this and I could be wrong.

**Comment by smeijer** [comment]
Thanks for the suggestion @andraspalasti! Much appreciated.

Unfortunately, it doesn't exactly do what we need, as `q` can also contain words that aren't valid tags.

I came up with this alternative implementation:

https://github.com/kentcdodds/remix-kentcdodds/blob/681ccda127a5ea672cb4b7e95813760cb1465a1b/app/routes/blog/index.tsx#L119-L131
