### ISSUE TITLE
qr code should be hidden on page load

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#35]
https://github.com/kentcdodds/remix-kentcdodds/pull/28#discussion_r664107524

**Comment by smeijer** [comment]
Added something quick. There is a timeout of 15 seconds, after which the QR reverts to the hidden state. For me, that was plenty to pick up the phone, open the camera app, and scan the QR. PR will be pushed soon(ish).

![qr](https://user-images.githubusercontent.com/1196524/125457520-326a3c9f-517c-45c2-abab-bc6ba2be31b4.gif)

**Comment by kentcdodds** [comment]
Yeah, I like that 👍 Thanks!
