### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/remix-kentcdodds#4]
You know how in Pokemon Go when you start the game you get to choose between yellow, red, and blue teams? For a long time I've wanted to have the same thing on my site. Why? I think it'd be cool to show little indicators on the site that show how many people of a given team are currently on a certain page and how many have been on that page in total. You know... for fun.

Tracking the page views (and time spent on pages) could also help a lot with the suggested articles we plan to put at the bottom of each article as well as feature on the home page.

A simple implementation of this could be done with sessions or local storage. A more legit version of this could involve user accounts which I think is a much bigger idea, but would unlock other cool things I'd like to do...

**Comment by kentcdodds** [comment]
I realize this is scope creep and I've been on the receiving end of that and it's no fun. Most of this scope creep involves backend implementation I think, and that's on me. I may be under estimating the impact to the design, but I think this should be simple enough to include in the current design.

What I envision:

1. An indicator of the logged in state for the user
2. Indicators for the number of team members who have read and are reading a particular post
3. Login/register and user settings pages

I think that should be it.

**Comment by kentcdodds** [comment]
Actually, the illustration of me on a snowboard/etc could be used on the page where users select their team. It could be themed after the available team colors (red, blue, and yellow) and then that character could appear throughout the site team indicators. Could be cool I think.

**Comment by kentcdodds** [comment]
The login flow works today in the deployed version of the repo: https://kentcdodds-remix.herokuapp.com/

If you want to see what pages are involved, you might register to see what the flow is like currently. Do a password reset and update your account name and email as well. If it doesn't work let me know, but it should work without trouble. The design is... nonexistent 😅

Here's a high level here are the important bits to everything:

1. Login/register page
2. Unconfirmed member settings page
3. Confirmed member settings page
4. Password reset page
5. Changing email requires password
6. Loading and Error states for all of this stuff (successful login/redirect animation, wrong password)

Thanks!

**Comment by dealingwith** [comment]
I created an account and logged in! My team is empty. How do you envision joining a team working?

> the page where users select their team

How many teams are there? Are new teams created automatically or by users (or there won't be any new teams after the initial N number of teams)?

**Comment by kentcdodds** [comment]
There are only three teams. Red, Blue, and Yellow. I envision the selection to be kinda like choosing a team in pokemon go: https://youtu.be/d-nMDn2Cki0

Maybe with less storyline 😅

I was thinking the illustrator could make three versions of this guy (they'd look the same except in different colors and I think the illustrator is going to put him on a snowboard instead of skates, but whatever it ends up being):

![image](https://user-images.githubusercontent.com/1500684/113606764-adcf9f00-9605-11eb-837c-c8ddfd9c33c2.png)

So yeah, a screen that shows three of those guys in red, blue, and yellow which you can select after you confirm your email address and it's a lifetime selection. Then all you get from there is some indication of which team your on (probably around where you click to manage your account). It could be a miniature icon of the character in the color you chose. Then on each blog post there would be the indication of how many members of each team has read that post and how many are reading it at the moment.

If that doesn't make sense I'd be happy to chat over video. I don't think it needs to be super elaborate.

**Comment by dealingwith** [comment]
> I was thinking the illustrator could make three versions of this guy

Chatting with Maggie, we think trying to scale the character down is a bad idea, and that just three colored dots might better accomplish the goal here. What do you think?

**Comment by kentcdodds** [comment]
That sounds good.

**Comment by kentcdodds** [comment]
Or maybe we could do the character's head, a helmet, a skate, a snowboard, or a onewheel icon?

**Comment by MaggieAppleton** [comment]
I can check with Mohamed about making 3 coloured versions of the character.

If we're just putting the character on the team selection page that would work. I was thinking it wouldn't work to scale the character down to icon-size (eg. to indicate someone's assigned team in the navbar, or indicating how many folks of a certain team have read an article).

Using coloured dots for any smaller activity indicators is definitely the way to go. But coloured characters can be part of the account creation/on-boarding

**Comment by kentcdodds** [comment]
> But coloured characters can be part of the account creation/on-boarding

Yes, that's what I was thinking as well 👍 Very cool. Looking forward to this :)

**Comment by kentcdodds** [comment]
Just had another idea that would be cool. We'll integrate with discord and in the KCD discord we'll have a role for each team and make their username in discord show up as that color! Yeeeha!

**Comment by kentcdodds** [comment]
So we're going to have a counter on each blog post for each team to show how many members of each team have read that post. I'm concerned this will lead to people just choosing the team with the most number of people.

So what I'm thinking of doing instead is not showing the number of people, but the percentage of members of a given team who have actually read the post. And to avoid with percentages as low as 3% (which wouldn't look good) we won't actually show the percentage, but do some kind of pie chart or something.

This has me thinking about [Ingress](https://www.ingress.com/game/) portals and Pokemon Go gyms where one team can "claim" it as their own. So we could say that whichever team has the highest percentage of their members who have read the post is the team that owns the post. This can be signified by showing the character in that team's color above a bar/pie chart. Maybe we could even show something that says: "Hey Yellow Team Member! The Red team owns this post for now, but if you get 30 more of your team to read it, then it's yours!"

I think that could be really fun.

**Comment by kentcdodds** [comment]
And we could have a private channel in discord for each of these teams so they can coordiante.

And perhaps their "readership" on a post can have a halflife of a year or so too...

Anyway, just a few things I'm thinking about with teams to make them extra fun.

**Comment by kentcdodds** [comment]
I'd say this is done 👍 Thanks team!
