### ISSUE TITLE
Don't show newsletter subscription form for subscribed users

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#44]
Converted from a note, which stated the following:

> If the user is logged in and already on the mailing list, we shouldn't show the newsletter subscription thing. Figure out what to render instead.

**Comment by smeijer** [comment]
@kentcdodds, how about showing the user that they're currently subscribed to the newsletter (and with what email), and provide them the option to unsubscribe, right there?

**Comment by kentcdodds** [comment]
I don't mind making it easy for people to unsubscribe, but I'm not a fan of directly inviting it so prominently either 😅

**Comment by kentcdodds** [comment]
Maybe it should just show "you're subscribed" and "manage your subscription" which will link them to what we build for #59

**Comment by kentcdodds** [comment]
This is implemented "well enough" for now (I just hide it 🤷‍♂️)
