### ISSUE TITLE
redirect `/chats` to `/chats/{lastSeason}`?

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#46]
Should `/chats` redirect to the most recent reason? Currently `/chats` renders the same content as `/chats/04`.

**Comment by kentcdodds** [comment]
I thought about that. I kinda like not having the extra season number on there, but I think you're right. It just makes more sense to redirect to the latest season. I'll do that.

**Comment by kentcdodds** [comment]
Forgot to reference this, but this is done 👍
