### ISSUE TITLE
Default to dark mode theme

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#51]
I think we should ignore the color scheme preference, and just default to dark mode. This site looks best in dark mode, and most people don't take the trouble of changing browser settings (which defaults to light mode). 

If they really prefer light mode, it's just one click away, and persisted in a cookie any ways.

TLDR; Default to dark mode, regardless of browser settings.

**Comment by kentcdodds** [comment]
Hmmmmmm...

> This site looks best in dark mode

I agree with you, but it's pretty subjective 😉 

I feel like since we already have things working with honoring people's settings we should keep it as it is. If they haven't updated their default settings to prefer dark mode even though that's what they do prefer, then they can change to dark mode. As you say, it's just a click away.

But I could be convinced otherwise. I'll ask our friends :)

**Comment by tsuki42** [comment]
I prefer dark mode so my thoughts on this may be a bit biased....
To make the best first impression, I think the site should be in the mode it looks the best in. The users can always apply their own preferences.

**Comment by Aprillion** [comment]
epicreact.dev defaults to dark mode regardless of my OS / browser settings => IMHO kent.dev can do the same

on the other hand, from first principles, it might be more educational if the site looked its best in both modes and followed user preferences - to encourage more developers to listen to users' preferences ¯\_(ツ)_/¯

**Comment by kentcdodds** [comment]
Yeah, I feel like it's an accessibility thing personally. I want to honor people's preferences. If someone prefers dark mode then they should update their preferences. If someone has explicitly ensured their preferences are light mode and we don't honor that, this could be very annoying.

https://twitter.com/ryanflorence/status/1369315010141327361?s=19

So I think we're going to leave the implementation as it is.

**Comment by kentcdodds** [comment]
Oh, one other thing I should mention is that if the user hasn't configured anything, then we do default to dark mode. We check whether [`prefers-color-scheme: light`](https://github.com/kentcdodds/remix-kentcdodds/blob/9b6c759bba51b67251d6e31f972f793234b5dfd2/app/utils/theme-provider.tsx#L17) and only then will we default to light mode.

I don't know whether user agents can/do leave that setting "unset" but if they do then those users will default to dark mode.

**Comment by smeijer** [comment]
Oh my, was I wrong; [almost 90%](https://twitter.com/kentcdodds/status/1415661473011961857?s=20) of the target audience seem to have set their settings to their prefered mode. :exploding_head:. _(Know your audience :sweat_smile:)_

> Oh, one other thing I should mention is that if the user hasn't configured anything, then we do default to dark mode.

That would have been the best, but as I understand, the `no-preference` didn't make it to the spec.

> This feature, like the other prefers-* features, previously had a no-preference value to indicate an author not expressing an active preference. However, user agents converged on expressing the "default" behavior as a light preference, and never matching no-preference.
If a future user agent wishes to expose a difference between "no preference" and "really wants a light display", please contact the CSSWG to discuss this.
> 
> - https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-color-scheme

**Comment by kentcdodds** [comment]
Bummer about the `no-preference` thing :(

**Comment by smeijer** [comment]
> it might be more educational if the site looked its best in both modes

I think we achieved that. Either I got used to light mode, or it does look better now :sweat_smile: . Thanks all!
