### ISSUE TITLE
randomize team order on Signup page

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#61]
I don't have the numbers, but I remember reading something once that order of options influences our choice. Maybe we should randomize the order of the team buttons on `/signup`, to maximize the chance of having equality weighted teams.

**Comment by kentcdodds** [comment]
Just remembered that randomizing things is a challenge with SSR 😅 But I just realized that you can do the randomization in the loader and poof, problem is gone! Man, I freaking love remix.
