### ISSUE TITLE
Put static stuff on a CDN

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/remix-kentcdodds#62]
We're doing this already with images. I think we should do it with fonts, the favicon, etc. It will free up the web server to focus on what it does well. I could probably use netlify. I'm pretty happy with them 👍

**Comment by kentcdodds** [comment]
Not sure whether I can/should just hook up the deployment process to publish the `public` directory to a CDN (so we'd include the CSS/JS built stuff as well). I'm not sure how big a deal it is to have the web server handle serving the static assets. It's probably fine I guess.

**Comment by kentcdodds** [comment]
Another thing on my mind here is redirects. I'd love to not have my server handle redirects and instead have a CDN handle that.

So I guess in general, I need to explore CDN integration with the website. How difficult would it be to integrate a CDN with the fly deployment?

**Comment by smeijer** [comment]
> Another thing on my mind here is redirects. I'd love to not have my server handle redirects and instead have a CDN handle that.

I'm curious as to why? Especially when you're deploying multi-region with fly.io. Redirects are very light for your server, and with fly they are handled in a region near your user. Isn't this just complicating things for little to no gain?

**Comment by kentcdodds** [comment]
Yeah, I'm over-thinking it. I'll handle redirects myself and I'll make sure cache headers are set appropriately for static assets.

**Comment by kentcdodds** [comment]
fly has a `[[statics]]` config and they'll act as the CDN for us automatically. Very cool 👍
