### ISSUE TITLE
[Suggestion] Reduce spacing of head elements at 4k resolution

### ISSUE THREAD

**Issue by tsteckenborn** [kentcdodds/remix-kentcdodds#64]
Hi all,

sorry to chime in here, but I would recommend reducing the spacing on large resolutions. For illustration see the attached screenshots.

![image](https://user-images.githubusercontent.com/50519619/126128563-8748d776-8947-4cd9-a19f-1c38f4d2cc28.png)
![image](https://user-images.githubusercontent.com/50519619/126128617-54e2460c-25be-4484-9a42-2f304a0d1d93.png)

**Comment by smeijer** [comment]
What's the screen size in inches?

**Comment by tsteckenborn** [comment]
It's a 27-inch display at 3840x2160.
