### ISSUE TITLE
Link preview for sharing on Discord/Twitter

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/remix-kentcdodds#7]
When you get around to adding link preview image for sharing blog posts on social media, presumably using https://ogp.me/ like `<meta property="og:image" content="..." />` (or using some Remix utility that would automate it), please consider showing a more compact preview that would take less vertical space than the current preview:
<img width="770" alt="Screenshot 2021-04-14 at 13 55 19" src="https://user-images.githubusercontent.com/1087670/114707009-01d73380-9d2a-11eb-9f5b-e09380d77c25.png">

IMHO something like these GitHub links would look best:
<img width="600" alt="Screenshot 2021-04-14 at 14 04 00" src="https://user-images.githubusercontent.com/1087670/114707348-65f9f780-9d2a-11eb-84c2-77799f2dbd6b.png">

Not sure how the black magic works exactly, some experimentation with https://ogp.me/#no_vertical might be needed. FTR, GitHub is using following for that particular page:
```html
<meta name="twitter:image:src" content="https://avatars.githubusercontent.com/u/1500684?s=400&amp;v=4" />
<meta name="twitter:site" content="@github" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="kentcdodds/esbuild-node-modules" />
<meta name="twitter:description" content="Contribute to kentcdodds/esbuild-node-modules development by creating an account on GitHub." />

<meta property="og:image" content="https://avatars.githubusercontent.com/u/1500684?s=400&amp;v=4" />
<meta property="og:site_name" content="GitHub" />
<meta property="og:type" content="object" />
<meta property="og:title" content="kentcdodds/esbuild-node-modules" />
<meta property="og:url" content="https://github.com/kentcdodds/esbuild-node-modules" />
<meta property="og:description" content="Contribute to kentcdodds/esbuild-node-modules development by creating an account on GitHub." />
```

**Comment by kentcdodds** [comment]
Thanks! I prefer the larger size. In case you didn't know, you can surround a link in `<` and `>` to disable the preview in discord. I do that sometimes when posting a lot of links.
