### ISSUE TITLE
deps: add `prettier-plugin-tailwind`

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#9]
This prettier plugin sorts classNames, helping to keep tailwind based projects organized.

From their readme:

---

**Go from this:**

```html
<div class="z-50 z-10 container  text-left md:text-center justify-center">
	...
</div>
```

**To this:**

```html
<div class="container justify-center text-left z-10 z-50 md:text-center">
	...
</div>
```

https://www.npmjs.com/package/prettier-plugin-tailwind

**Comment by kentcdodds** [comment]
Yes 👍 I'll get this added. Thanks!
