### ISSUE TITLE
logout action doesn't update `useOptionalUser`

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#96]
Due to this, the navbar is still showing the profile image after logout.

https://github.com/kentcdodds/remix-kentcdodds/blob/d97b3fe8c607eae3942c82e252fe78d0efeaddf3/app/components/navbar.tsx#L239-L240

**Comment by kentcdodds** [comment]
This is a bug in the experimental version of remix and should be fixed in the next few days when we get a stable release. I let @ryanflorence know already :) (Ryan, it's the one where the root loader isn't getting called after actions).

**Comment by kentcdodds** [comment]
This is fixed. It was my fault. Loaders are only re-called after actions. Not on redirects from other loaders. So I switched this to an action and it works great now.
